version: '3.8'
services:
  app:
    build: .
    container_name: shortened_api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:teddy@mysql:3306/shorteneddb
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/api
      - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teddy
      MYSQL_DATABASE: shorteneddb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data: